services:
  - type: web
    name: smarttech-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smarttech-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: OPENROUTER_API_KEY_1
        sync: false
      - key: OPENROUTER_API_KEY_2
        sync: false
      - key: OPENROUTER_API_KEY_3
        sync: false
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: RENDER
        value: "true"
    runtime: python-3.12.6

databases:
  - name: smarttech-db
    plan: free