services:
  - type: web
    name: smarttech-backend
    env: python
    plan: free
    buildCommand: |
      # Force Python 3.12.6
      apt-get update
      apt-get install -y gcc libpq-dev python3.12-dev python3.12-venv
      python3.12 -m venv .venv
      source .venv/bin/activate
      pip install --upgrade pip
      pip install --no-cache-dir psycopg2-binary==2.9.9
      pip install -r requirements.txt
    startCommand: |
      source .venv/bin/activate
      python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.6"
      - key: DATABASE_URL
        fromDatabase:
          name: smarttech-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: OPENROUTER_API_KEY_1
        sync: false
      - key: OPENROUTER_API_KEY_2
        sync: false
      - key: OPENROUTER_API_KEY_3
        sync: false
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: RENDER
        value: "true"
    runtime: python-3.12.6

databases:
  - name: smarttech-db
    plan: free